#!/bin/bash

get_name() {
  name=`gconftool-2 --get "$1/visible_name"`
}

get_profiles() {
  profiles=`gconftool-2 --all-dirs /apps/gnome-terminal/profiles`
}

get_path() {
  get_profiles
  for i in $profiles; do
    get_name "$i"
    if test "$name" == "$1" ; then
      path="$i"
    fi
  done
}

read_palette() {
  palette=`cat $1.palette`
}

set_palette() {
  get_path "$1"
  read_palette "$1"
  palette=`gconftool-2 --set "$path/palette" --type=string "$palette"`
}

set_palette agnostic
set_palette agnostic-dark


